# Generated by Django 4.1.3 on 2022-12-01 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("traits", "0002_trait_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trait",
            name="pets",
        ),
    ]
