# Generated by Django 4.1.3 on 2022-12-02 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traits", "0003_remove_trait_pets"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trait",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
